# training args
seed: 519
lr: 0.001
snapshot_pref: "./TestExps/Avel/"
batch_size: 64
test_batch_size: 64
n_epoch: 45
gpu: "0"
evaluate: False
resume: ""    # path to latest checkpoint

# dataset args
dataset_name: "dy"
category_num: 10
vis_fea_type: "vgg"

# model args
model: "avel"
# threshold_value: 0.099

# logs args
print_freq: 200
eval_freq: 1

# 控制梯度的
clip_gradient: 0.1

# losses args
avps_flag: False
lambda_avps: 100
vcon_flag: True
lambda_vcon: 1
scon_flag: True
lambda_scon: 0.01

# addtional
data_root: "/data1/yyp/AVEL/generalization_exp_data/pm_selected/features"
meta_root: "/data1/cy/nips/dataset/csvfiles/"
ave: False
avepm: True
is_select: True
audio_preprocess_mode: "None"
preprocess: "None"
a_feature_root: "/data1/lwy/ave-pm-dataset/data/"
v_feature_root: "dataset/feature/preprocess_visual_feature"