cd CMBS/
python supv_main.py \
--gpu 0 \
--lr 0.0007 \
--clip_gradient 0.5 \
--snapshot_pref "./Exps/" \
--n_epoch 200 \
--b 64 \
--test_batch_size 16 \
--print_freq 100 \
--avepm True \
--ave false \
--preprocess 'None' \
--audio_preprocess 'None' \
--is_select false \
--data_root "dataset/feature/features/" \
--meta_root "dataset/csvfiles/" \
--v_feature_root "dataset/feature/preprocess_visual_feature" \
--a_feature_root "dataset/feature/preprocess_audio_feature" \